# Copyright 2018 The original authors.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 
name: Integration Tests

env:
  MAVEN_ARGS: -B -e

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  kubernetes:
    name: Kubernetes Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        kubernetes: [v1.20.1]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Minikube-Kubernetes
        uses: manusa/actions-setup-minikube@v2.4.1
        with:
          minikube version: v1.16.0
          kubernetes version: ${{ matrix.kubernetes }}
          github token: ${{ secrets.GITHUB_TOKEN }}
          start args: '--addons=metrics-server --force'
      - name: Setup Java 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Integration Tests
        run: |
      - name: Install and Run Integration Tests
        run: |
          minikube addons enable registry
          echo "Registry: $(minikube ip):5000"
          mvn -B clean install -Presources -Pwith-examples -Pwith-tests -Duser.name=dekorateio -Ddekorate.docker.registry=$(minikube ip):5000 -Dformat.skip=true

  openshift:
    name: Openshift Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        openshift: [v3.11.0]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup OpenShift
        uses: manusa/actions-setup-openshift@v1.1.3
        with:
          oc version: ${{ matrix.openshift }}
          github token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Java 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Integration Tests
        run: |
          oc login -u system:admin
          oc new-project itests
          oc get projects
          oc get services -n default
          oc port-forward -n default service/docker-registry 8888:5000
          echo "Registry: localhost:8888"
          oc import-image fabric8/s2i-java:2.3 --from=docker.io/fabric8/s2i-java:2.3 --confirm
          oc tag --source docker docker.io/fabric8/s2i-java:2.3 s2i-java:2.3
          mvn -B clean install -Presources -Pwith-examples -Pwith-tests -Duser.name=dekorateio -Ddekorate.docker.registry=localhost:8888 -Dformat.skip=true
